### ISSUE TITLE
Validate the input

### ISSUE THREAD

**Issue by CodelineAtyab** [Najlaalrajhia98/TIC.TAC-TOE#1]
https://github.com/Najlaalrajhia98/TIC.TAC-TOE/blob/50bb70b7d55c11556f8fc98b75c777d4aa4dd4d1/src/TICTAC.java#L39

We would need to validate the input and until the input is invalid we week keep asking about the input again and again.

**Comment by Najlaalrajhia98** [comment]
done with validation
